defaults: &defaults
  app_name: Nporeach
  from_email: support@nporeach.com
  base_domain: nporeach.com

  gateway: bogus
  credentials:
    gateway:
      :login: demo
      :password: password
    paypal:
      :login: demo
      :password: password
      :signature: signature
    
development:
  <<: *defaults
  base_domain: nporeach.dev:3000 # Edit /etc/hosts to add subscriptions.dev, test.subscriptions.dev, etc., or use Pow: http://pow.cx

test:
  <<: *defaults

production:
  <<: *defaults
  credentials:
    gateway:
      :login: demo
      :password: password
    paypal:
      :login: demo
      :password: password
      :signature: signature
